services:
  postgres-db:
    image: postgres:15-alpine
    container_name: website_checker_postgres
    environment:
      POSTGRES_USER: rise
      POSTGRES_PASSWORD: password
      POSTGRES_DB: website_checker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db/schema.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: website_checker_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/website_checker_db

volumes:
  postgres_data: