spring:
  application:
    name: watchDog
  datasource:
    # Connects to the local database we will define in the docker-compose file below
    url: jdbc:postgresql://localhost:5434/watchdog
    username: rise
    password: password
    driver-class-name: org.postgresql.Driver

  # Optional: Helpful for debugging raw SQL (though JdbcTemplate doesn't log the same way JPA does)
  # You can turn up logging for the JDBC template specifically
  logging:
    level:
      org.springframework.jdbc.core.JdbcTemplate: DEBUG
server:
  port: 8080

